// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.twjitm.core.common.proto;

public final class BaseMessageProto {
  private BaseMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMessageProBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseMessageProBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 SESSION_ID = 1;</code>
     */
    long getSessionId();

    /**
     * <code>int32 commid = 2;</code>
     */
    int getCommid();

    /**
     * <code>int32 length = 3;</code>
     */
    int getLength();

    /**
     * <code>int64 uId = 4;</code>
     */
    long getUId();

    /**
     * <code>int64 timeStamp = 5;</code>
     */
    long getTimeStamp();
  }
  /**
   * Protobuf type {@code BaseMessageProBuf}
   */
  public  static final class BaseMessageProBuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseMessageProBuf)
      BaseMessageProBufOrBuilder {
    // Use BaseMessageProBuf.newBuilder() to construct.
    private BaseMessageProBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMessageProBuf() {
      sessionId_ = 0L;
      commid_ = 0;
      length_ = 0;
      uId_ = 0L;
      timeStamp_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseMessageProBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sessionId_ = input.readInt64();
              break;
            }
            case 16: {

              commid_ = input.readInt32();
              break;
            }
            case 24: {

              length_ = input.readInt32();
              break;
            }
            case 32: {

              uId_ = input.readInt64();
              break;
            }
            case 40: {

              timeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseMessageProto.internal_static_BaseMessageProBuf_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseMessageProto.internal_static_BaseMessageProBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseMessageProBuf.class, Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <code>int64 SESSION_ID = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int COMMID_FIELD_NUMBER = 2;
    private int commid_;
    /**
     * <code>int32 commid = 2;</code>
     */
    public int getCommid() {
      return commid_;
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private int length_;
    /**
     * <code>int32 length = 3;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int UID_FIELD_NUMBER = 4;
    private long uId_;
    /**
     * <code>int64 uId = 4;</code>
     */
    public long getUId() {
      return uId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timeStamp_;
    /**
     * <code>int64 timeStamp = 5;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (commid_ != 0) {
        output.writeInt32(2, commid_);
      }
      if (length_ != 0) {
        output.writeInt32(3, length_);
      }
      if (uId_ != 0L) {
        output.writeInt64(4, uId_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(5, timeStamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (commid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, commid_);
      }
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, length_);
      }
      if (uId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, uId_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timeStamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BaseMessageProBuf)) {
        return super.equals(obj);
      }
      BaseMessageProBuf other = (BaseMessageProBuf) obj;

      boolean result = true;
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && (getCommid()
          == other.getCommid());
      result = result && (getLength()
          == other.getLength());
      result = result && (getUId()
          == other.getUId());
      result = result && (getTimeStamp()
          == other.getTimeStamp());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + COMMID_FIELD_NUMBER;
      hash = (53 * hash) + getCommid();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUId());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BaseMessageProBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMessageProBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMessageProBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMessageProBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMessageProBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMessageProBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMessageProBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BaseMessageProBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMessageProBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMessageProBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BaseMessageProBuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseMessageProBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseMessageProBuf)
        BaseMessageProBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseMessageProto.internal_static_BaseMessageProBuf_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseMessageProto.internal_static_BaseMessageProBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseMessageProBuf.class, Builder.class);
      }

      // Construct using com.twjitm.common.proto.BaseMessageProto.BaseMessageProBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sessionId_ = 0L;

        commid_ = 0;

        length_ = 0;

        uId_ = 0L;

        timeStamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseMessageProto.internal_static_BaseMessageProBuf_descriptor;
      }

      public BaseMessageProBuf getDefaultInstanceForType() {
        return BaseMessageProBuf.getDefaultInstance();
      }

      public BaseMessageProBuf build() {
        BaseMessageProBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BaseMessageProBuf buildPartial() {
        BaseMessageProBuf result = new BaseMessageProBuf(this);
        result.sessionId_ = sessionId_;
        result.commid_ = commid_;
        result.length_ = length_;
        result.uId_ = uId_;
        result.timeStamp_ = timeStamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseMessageProBuf) {
          return mergeFrom((BaseMessageProBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseMessageProBuf other) {
        if (other == BaseMessageProBuf.getDefaultInstance()) return this;
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.getCommid() != 0) {
          setCommid(other.getCommid());
        }
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (other.getUId() != 0L) {
          setUId(other.getUId());
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseMessageProBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseMessageProBuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 SESSION_ID = 1;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 SESSION_ID = 1;</code>
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 SESSION_ID = 1;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private int commid_ ;
      /**
       * <code>int32 commid = 2;</code>
       */
      public int getCommid() {
        return commid_;
      }
      /**
       * <code>int32 commid = 2;</code>
       */
      public Builder setCommid(int value) {
        
        commid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 commid = 2;</code>
       */
      public Builder clearCommid() {
        
        commid_ = 0;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <code>int32 length = 3;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>int32 length = 3;</code>
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }

      private long uId_ ;
      /**
       * <code>int64 uId = 4;</code>
       */
      public long getUId() {
        return uId_;
      }
      /**
       * <code>int64 uId = 4;</code>
       */
      public Builder setUId(long value) {
        
        uId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uId = 4;</code>
       */
      public Builder clearUId() {
        
        uId_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>int64 timeStamp = 5;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>int64 timeStamp = 5;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeStamp = 5;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BaseMessageProBuf)
    }

    // @@protoc_insertion_point(class_scope:BaseMessageProBuf)
    private static final BaseMessageProBuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BaseMessageProBuf();
    }

    public static BaseMessageProBuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMessageProBuf>
        PARSER = new com.google.protobuf.AbstractParser<BaseMessageProBuf>() {
      public BaseMessageProBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BaseMessageProBuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMessageProBuf> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BaseMessageProBuf> getParserForType() {
      return PARSER;
    }

    public BaseMessageProBuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatMessageProBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatMessageProBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 chatType = 1;</code>
     */
    int getChatType();

    /**
     * <code>string context = 2;</code>
     */
    String getContext();
    /**
     * <code>string context = 2;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();

    /**
     * <code>int64 receiveUId = 3;</code>
     */
    long getReceiveUId();

    /**
     * <code>string receiveSession = 4;</code>
     */
    String getReceiveSession();
    /**
     * <code>string receiveSession = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceiveSessionBytes();

    /**
     * <code>string receiveNickName = 5;</code>
     */
    String getReceiveNickName();
    /**
     * <code>string receiveNickName = 5;</code>
     */
    com.google.protobuf.ByteString
        getReceiveNickNameBytes();

    /**
     * <code>string receiveHaldUrl = 6;</code>
     */
    String getReceiveHaldUrl();
    /**
     * <code>string receiveHaldUrl = 6;</code>
     */
    com.google.protobuf.ByteString
        getReceiveHaldUrlBytes();

    /**
     * <code>bool read = 7;</code>
     */
    boolean getRead();

    /**
     * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
     */
    boolean hasBaseMessageBuf();
    /**
     * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
     */
    BaseMessageProBuf getBaseMessageBuf();
    /**
     * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
     */
    BaseMessageProBufOrBuilder getBaseMessageBufOrBuilder();
  }
  /**
   * Protobuf type {@code ChatMessageProBuf}
   */
  public  static final class ChatMessageProBuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatMessageProBuf)
      ChatMessageProBufOrBuilder {
    // Use ChatMessageProBuf.newBuilder() to construct.
    private ChatMessageProBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessageProBuf() {
      chatType_ = 0;
      context_ = "";
      receiveUId_ = 0L;
      receiveSession_ = "";
      receiveNickName_ = "";
      receiveHaldUrl_ = "";
      read_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChatMessageProBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              chatType_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              context_ = s;
              break;
            }
            case 24: {

              receiveUId_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              receiveSession_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              receiveNickName_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              receiveHaldUrl_ = s;
              break;
            }
            case 56: {

              read_ = input.readBool();
              break;
            }
            case 66: {
              BaseMessageProBuf.Builder subBuilder = null;
              if (baseMessageBuf_ != null) {
                subBuilder = baseMessageBuf_.toBuilder();
              }
              baseMessageBuf_ = input.readMessage(BaseMessageProBuf.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseMessageBuf_);
                baseMessageBuf_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseMessageProto.internal_static_ChatMessageProBuf_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseMessageProto.internal_static_ChatMessageProBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMessageProBuf.class, Builder.class);
    }

    public static final int CHATTYPE_FIELD_NUMBER = 1;
    private int chatType_;
    /**
     * <code>int32 chatType = 1;</code>
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int CONTEXT_FIELD_NUMBER = 2;
    private volatile Object context_;
    /**
     * <code>string context = 2;</code>
     */
    public String getContext() {
      Object ref = context_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        context_ = s;
        return s;
      }
    }
    /**
     * <code>string context = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVEUID_FIELD_NUMBER = 3;
    private long receiveUId_;
    /**
     * <code>int64 receiveUId = 3;</code>
     */
    public long getReceiveUId() {
      return receiveUId_;
    }

    public static final int RECEIVESESSION_FIELD_NUMBER = 4;
    private volatile Object receiveSession_;
    /**
     * <code>string receiveSession = 4;</code>
     */
    public String getReceiveSession() {
      Object ref = receiveSession_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receiveSession_ = s;
        return s;
      }
    }
    /**
     * <code>string receiveSession = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveSessionBytes() {
      Object ref = receiveSession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receiveSession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVENICKNAME_FIELD_NUMBER = 5;
    private volatile Object receiveNickName_;
    /**
     * <code>string receiveNickName = 5;</code>
     */
    public String getReceiveNickName() {
      Object ref = receiveNickName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receiveNickName_ = s;
        return s;
      }
    }
    /**
     * <code>string receiveNickName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveNickNameBytes() {
      Object ref = receiveNickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receiveNickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVEHALDURL_FIELD_NUMBER = 6;
    private volatile Object receiveHaldUrl_;
    /**
     * <code>string receiveHaldUrl = 6;</code>
     */
    public String getReceiveHaldUrl() {
      Object ref = receiveHaldUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receiveHaldUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string receiveHaldUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveHaldUrlBytes() {
      Object ref = receiveHaldUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receiveHaldUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int READ_FIELD_NUMBER = 7;
    private boolean read_;
    /**
     * <code>bool read = 7;</code>
     */
    public boolean getRead() {
      return read_;
    }

    public static final int BASEMESSAGEBUF_FIELD_NUMBER = 8;
    private BaseMessageProBuf baseMessageBuf_;
    /**
     * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
     */
    public boolean hasBaseMessageBuf() {
      return baseMessageBuf_ != null;
    }
    /**
     * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
     */
    public BaseMessageProBuf getBaseMessageBuf() {
      return baseMessageBuf_ == null ? BaseMessageProBuf.getDefaultInstance() : baseMessageBuf_;
    }
    /**
     * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
     */
    public BaseMessageProBufOrBuilder getBaseMessageBufOrBuilder() {
      return getBaseMessageBuf();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chatType_ != 0) {
        output.writeInt32(1, chatType_);
      }
      if (!getContextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, context_);
      }
      if (receiveUId_ != 0L) {
        output.writeInt64(3, receiveUId_);
      }
      if (!getReceiveSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiveSession_);
      }
      if (!getReceiveNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, receiveNickName_);
      }
      if (!getReceiveHaldUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, receiveHaldUrl_);
      }
      if (read_ != false) {
        output.writeBool(7, read_);
      }
      if (baseMessageBuf_ != null) {
        output.writeMessage(8, getBaseMessageBuf());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chatType_);
      }
      if (!getContextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, context_);
      }
      if (receiveUId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, receiveUId_);
      }
      if (!getReceiveSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiveSession_);
      }
      if (!getReceiveNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, receiveNickName_);
      }
      if (!getReceiveHaldUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, receiveHaldUrl_);
      }
      if (read_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, read_);
      }
      if (baseMessageBuf_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getBaseMessageBuf());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMessageProBuf)) {
        return super.equals(obj);
      }
      ChatMessageProBuf other = (ChatMessageProBuf) obj;

      boolean result = true;
      result = result && (getChatType()
          == other.getChatType());
      result = result && getContext()
          .equals(other.getContext());
      result = result && (getReceiveUId()
          == other.getReceiveUId());
      result = result && getReceiveSession()
          .equals(other.getReceiveSession());
      result = result && getReceiveNickName()
          .equals(other.getReceiveNickName());
      result = result && getReceiveHaldUrl()
          .equals(other.getReceiveHaldUrl());
      result = result && (getRead()
          == other.getRead());
      result = result && (hasBaseMessageBuf() == other.hasBaseMessageBuf());
      if (hasBaseMessageBuf()) {
        result = result && getBaseMessageBuf()
            .equals(other.getBaseMessageBuf());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
      hash = (37 * hash) + RECEIVEUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiveUId());
      hash = (37 * hash) + RECEIVESESSION_FIELD_NUMBER;
      hash = (53 * hash) + getReceiveSession().hashCode();
      hash = (37 * hash) + RECEIVENICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiveNickName().hashCode();
      hash = (37 * hash) + RECEIVEHALDURL_FIELD_NUMBER;
      hash = (53 * hash) + getReceiveHaldUrl().hashCode();
      hash = (37 * hash) + READ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRead());
      if (hasBaseMessageBuf()) {
        hash = (37 * hash) + BASEMESSAGEBUF_FIELD_NUMBER;
        hash = (53 * hash) + getBaseMessageBuf().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMessageProBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessageProBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessageProBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatMessageProBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessageProBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessageProBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMessageProBuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatMessageProBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatMessageProBuf)
        ChatMessageProBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseMessageProto.internal_static_ChatMessageProBuf_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseMessageProto.internal_static_ChatMessageProBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMessageProBuf.class, Builder.class);
      }

      // Construct using com.twjitm.common.proto.BaseMessageProto.ChatMessageProBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chatType_ = 0;

        context_ = "";

        receiveUId_ = 0L;

        receiveSession_ = "";

        receiveNickName_ = "";

        receiveHaldUrl_ = "";

        read_ = false;

        if (baseMessageBufBuilder_ == null) {
          baseMessageBuf_ = null;
        } else {
          baseMessageBuf_ = null;
          baseMessageBufBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseMessageProto.internal_static_ChatMessageProBuf_descriptor;
      }

      public ChatMessageProBuf getDefaultInstanceForType() {
        return ChatMessageProBuf.getDefaultInstance();
      }

      public ChatMessageProBuf build() {
        ChatMessageProBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ChatMessageProBuf buildPartial() {
        ChatMessageProBuf result = new ChatMessageProBuf(this);
        result.chatType_ = chatType_;
        result.context_ = context_;
        result.receiveUId_ = receiveUId_;
        result.receiveSession_ = receiveSession_;
        result.receiveNickName_ = receiveNickName_;
        result.receiveHaldUrl_ = receiveHaldUrl_;
        result.read_ = read_;
        if (baseMessageBufBuilder_ == null) {
          result.baseMessageBuf_ = baseMessageBuf_;
        } else {
          result.baseMessageBuf_ = baseMessageBufBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMessageProBuf) {
          return mergeFrom((ChatMessageProBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMessageProBuf other) {
        if (other == ChatMessageProBuf.getDefaultInstance()) return this;
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (!other.getContext().isEmpty()) {
          context_ = other.context_;
          onChanged();
        }
        if (other.getReceiveUId() != 0L) {
          setReceiveUId(other.getReceiveUId());
        }
        if (!other.getReceiveSession().isEmpty()) {
          receiveSession_ = other.receiveSession_;
          onChanged();
        }
        if (!other.getReceiveNickName().isEmpty()) {
          receiveNickName_ = other.receiveNickName_;
          onChanged();
        }
        if (!other.getReceiveHaldUrl().isEmpty()) {
          receiveHaldUrl_ = other.receiveHaldUrl_;
          onChanged();
        }
        if (other.getRead() != false) {
          setRead(other.getRead());
        }
        if (other.hasBaseMessageBuf()) {
          mergeBaseMessageBuf(other.getBaseMessageBuf());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChatMessageProBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChatMessageProBuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int chatType_ ;
      /**
       * <code>int32 chatType = 1;</code>
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <code>int32 chatType = 1;</code>
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chatType = 1;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private Object context_ = "";
      /**
       * <code>string context = 2;</code>
       */
      public String getContext() {
        Object ref = context_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string context = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string context = 2;</code>
       */
      public Builder setContext(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string context = 2;</code>
       */
      public Builder clearContext() {
        
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>string context = 2;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        context_ = value;
        onChanged();
        return this;
      }

      private long receiveUId_ ;
      /**
       * <code>int64 receiveUId = 3;</code>
       */
      public long getReceiveUId() {
        return receiveUId_;
      }
      /**
       * <code>int64 receiveUId = 3;</code>
       */
      public Builder setReceiveUId(long value) {
        
        receiveUId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 receiveUId = 3;</code>
       */
      public Builder clearReceiveUId() {
        
        receiveUId_ = 0L;
        onChanged();
        return this;
      }

      private Object receiveSession_ = "";
      /**
       * <code>string receiveSession = 4;</code>
       */
      public String getReceiveSession() {
        Object ref = receiveSession_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          receiveSession_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string receiveSession = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveSessionBytes() {
        Object ref = receiveSession_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receiveSession_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiveSession = 4;</code>
       */
      public Builder setReceiveSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiveSession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiveSession = 4;</code>
       */
      public Builder clearReceiveSession() {
        
        receiveSession_ = getDefaultInstance().getReceiveSession();
        onChanged();
        return this;
      }
      /**
       * <code>string receiveSession = 4;</code>
       */
      public Builder setReceiveSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiveSession_ = value;
        onChanged();
        return this;
      }

      private Object receiveNickName_ = "";
      /**
       * <code>string receiveNickName = 5;</code>
       */
      public String getReceiveNickName() {
        Object ref = receiveNickName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          receiveNickName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string receiveNickName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveNickNameBytes() {
        Object ref = receiveNickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receiveNickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiveNickName = 5;</code>
       */
      public Builder setReceiveNickName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiveNickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiveNickName = 5;</code>
       */
      public Builder clearReceiveNickName() {
        
        receiveNickName_ = getDefaultInstance().getReceiveNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string receiveNickName = 5;</code>
       */
      public Builder setReceiveNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiveNickName_ = value;
        onChanged();
        return this;
      }

      private Object receiveHaldUrl_ = "";
      /**
       * <code>string receiveHaldUrl = 6;</code>
       */
      public String getReceiveHaldUrl() {
        Object ref = receiveHaldUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          receiveHaldUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string receiveHaldUrl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveHaldUrlBytes() {
        Object ref = receiveHaldUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receiveHaldUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiveHaldUrl = 6;</code>
       */
      public Builder setReceiveHaldUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiveHaldUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiveHaldUrl = 6;</code>
       */
      public Builder clearReceiveHaldUrl() {
        
        receiveHaldUrl_ = getDefaultInstance().getReceiveHaldUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string receiveHaldUrl = 6;</code>
       */
      public Builder setReceiveHaldUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiveHaldUrl_ = value;
        onChanged();
        return this;
      }

      private boolean read_ ;
      /**
       * <code>bool read = 7;</code>
       */
      public boolean getRead() {
        return read_;
      }
      /**
       * <code>bool read = 7;</code>
       */
      public Builder setRead(boolean value) {
        
        read_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool read = 7;</code>
       */
      public Builder clearRead() {
        
        read_ = false;
        onChanged();
        return this;
      }

      private BaseMessageProBuf baseMessageBuf_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          BaseMessageProBuf, BaseMessageProBuf.Builder, BaseMessageProBufOrBuilder> baseMessageBufBuilder_;
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public boolean hasBaseMessageBuf() {
        return baseMessageBufBuilder_ != null || baseMessageBuf_ != null;
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public BaseMessageProBuf getBaseMessageBuf() {
        if (baseMessageBufBuilder_ == null) {
          return baseMessageBuf_ == null ? BaseMessageProBuf.getDefaultInstance() : baseMessageBuf_;
        } else {
          return baseMessageBufBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public Builder setBaseMessageBuf(BaseMessageProBuf value) {
        if (baseMessageBufBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseMessageBuf_ = value;
          onChanged();
        } else {
          baseMessageBufBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public Builder setBaseMessageBuf(
          BaseMessageProBuf.Builder builderForValue) {
        if (baseMessageBufBuilder_ == null) {
          baseMessageBuf_ = builderForValue.build();
          onChanged();
        } else {
          baseMessageBufBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public Builder mergeBaseMessageBuf(BaseMessageProBuf value) {
        if (baseMessageBufBuilder_ == null) {
          if (baseMessageBuf_ != null) {
            baseMessageBuf_ =
              BaseMessageProBuf.newBuilder(baseMessageBuf_).mergeFrom(value).buildPartial();
          } else {
            baseMessageBuf_ = value;
          }
          onChanged();
        } else {
          baseMessageBufBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public Builder clearBaseMessageBuf() {
        if (baseMessageBufBuilder_ == null) {
          baseMessageBuf_ = null;
          onChanged();
        } else {
          baseMessageBuf_ = null;
          baseMessageBufBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public BaseMessageProBuf.Builder getBaseMessageBufBuilder() {
        
        onChanged();
        return getBaseMessageBufFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      public BaseMessageProBufOrBuilder getBaseMessageBufOrBuilder() {
        if (baseMessageBufBuilder_ != null) {
          return baseMessageBufBuilder_.getMessageOrBuilder();
        } else {
          return baseMessageBuf_ == null ?
              BaseMessageProBuf.getDefaultInstance() : baseMessageBuf_;
        }
      }
      /**
       * <code>.BaseMessageProBuf baseMessageBuf = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BaseMessageProBuf, BaseMessageProBuf.Builder, BaseMessageProBufOrBuilder>
          getBaseMessageBufFieldBuilder() {
        if (baseMessageBufBuilder_ == null) {
          baseMessageBufBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BaseMessageProBuf, BaseMessageProBuf.Builder, BaseMessageProBufOrBuilder>(
                  getBaseMessageBuf(),
                  getParentForChildren(),
                  isClean());
          baseMessageBuf_ = null;
        }
        return baseMessageBufBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ChatMessageProBuf)
    }

    // @@protoc_insertion_point(class_scope:ChatMessageProBuf)
    private static final ChatMessageProBuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMessageProBuf();
    }

    public static ChatMessageProBuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessageProBuf>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessageProBuf>() {
      public ChatMessageProBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatMessageProBuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessageProBuf> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMessageProBuf> getParserForType() {
      return PARSER;
    }

    public ChatMessageProBuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMessageProBuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseMessageProBuf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMessageProBuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMessageProBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nchat.proto\"f\n\021BaseMessageProBuf\022\021\n\tses" +
      "sionId\030\001 \001(\003\022\016\n\006commid\030\002 \001(\005\022\016\n\006length\030\003" +
      " \001(\005\022\013\n\003uId\030\004 \001(\003\022\021\n\ttimeStamp\030\005 \001(\003\"\315\001\n" +
      "\021ChatMessageProBuf\022\020\n\010chatType\030\001 \001(\005\022\017\n\007" +
      "context\030\002 \001(\t\022\022\n\nreceiveUId\030\003 \001(\003\022\026\n\016rec" +
      "eiveSession\030\004 \001(\t\022\027\n\017receiveNickName\030\005 \001" +
      "(\t\022\026\n\016receiveHaldUrl\030\006 \001(\t\022\014\n\004read\030\007 \001(\010" +
      "\022*\n\016baseMessageBuf\030\010 \001(\0132\022.BaseMessagePr" +
      "oBufB+\n\027com.twjitm.common.protoB\020BaseMes" +
      "sageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseMessageProBuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseMessageProBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseMessageProBuf_descriptor,
        new String[] { "SessionId", "Commid", "Length", "UId", "TimeStamp", });
    internal_static_ChatMessageProBuf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChatMessageProBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMessageProBuf_descriptor,
        new String[] { "ChatType", "Context", "ReceiveUId", "ReceiveSession", "ReceiveNickName", "ReceiveHaldUrl", "Read", "BaseMessageBuf", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
